# Faça um programa que leia um número inteiro qualquer e mostre na tela a sua tabuada.
n =int(input('Digite um número'))
print('{} X {:2} e {} '.format(n, 1, (n*1)))
print('{} X {:2} e {} '.format(n, 2, (n*2)))
print('{} X {:2} e {} '.format(n, 3, (n*3)))
print('{} X {:2} e {} '.format(n, 4, (n*4)))
print('{} X {:2} e {} '.format(n, 5, (n*5)))
print('{} X {:2} e {} '.format(n, 6, (n*6)))
print('{} X {:2} e {} '.format(n, 7, (n*7)))
print('{} X {:2} e {} '.format(n, 8, (n*8)))
print('{} X {:2} e {} '.format(n, 9, (n*9)))
print('{} X {:2} e {} '.format(n, 10, (n*10)))
print('{} X {:2} e {} '.format(n, 0, (n*0)))
